import esbuild from 'esbuild';
import process from 'process';
import { readFile } from 'node:fs/promises';
import { builtinModules } from 'node:module';

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */`;
const prod = process.argv[2] === 'production';

// drawio's vendored viewer.min.js contains a MathJax-from-CDN loader that injects
// an external <script> (createElement("script") + src=URL). Our offline previews
// never load MathJax, so this code path is dead — but shipping it (a) trips plugin
// review scanners that flag dynamic external-script injection, and (b) is the only
// createElement("script") in the vendored blob. We strip exactly that loader at
// build time, keeping the committed viewer.min.txt a pristine, diffable copy of
// upstream. The replacement count is asserted so a future drawio bump that changes
// the minified shape fails the build loudly instead of silently re-introducing it.
const VIEWER_SCRIPT_LOADER =
  'var Z=document.createElement("script");Z.setAttribute("type","text/javascript");' +
  'Z.setAttribute("src",k);z[0].parentNode.appendChild(Z)';

const sanitizeDrawioViewerPlugin = {
  name: 'sanitize-drawio-viewer',
  setup(build) {
    build.onLoad({ filter: /viewer\.min\.txt$/ }, async (args) => {
      const original = await readFile(args.path, 'utf8');
      const count = original.split(VIEWER_SCRIPT_LOADER).length - 1;
      if (count !== 1) {
        throw new Error(
          `sanitize-drawio-viewer: expected exactly 1 external-script loader in ` +
          `viewer.min.txt, found ${count}. The vendored drawio viewer likely ` +
          `changed; review and update VIEWER_SCRIPT_LOADER in esbuild.config.mjs.`,
        );
      }
      const contents = original.split(VIEWER_SCRIPT_LOADER).join('');
      if (contents.includes('createElement("script")') || contents.includes("createElement('script')")) {
        throw new Error(
          'sanitize-drawio-viewer: createElement("script") still present after ' +
          'stripping the known loader; aborting to avoid shipping it.',
        );
      }
      return { contents, loader: 'text' };
    });
  },
};

const context = await esbuild.context({
  plugins: [sanitizeDrawioViewerPlugin],
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian', 'electron',
    '@codemirror/autocomplete', '@codemirror/collab', '@codemirror/commands',
    '@codemirror/language', '@codemirror/lint', '@codemirror/search',
    '@codemirror/state', '@codemirror/view',
    '@lezer/common', '@lezer/highlight', '@lezer/lr',
    ...builtinModules,
    'node:*',
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  loader: { '.txt': 'text' },
  outfile: 'main.js',
  minify: prod,
});

if (prod) { await context.rebuild(); await context.dispose(); process.exit(0); }
else { await context.watch(); }
